services:
  db:
    image: mysql:5.7.40
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'sportshop'

    ports:
      - "3307:3306"
    expose:
      - '3306'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sportshop-app-local

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/sportshop'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '123456'
      VNPAY_RETURN_URL: 'http://sportshopn11.lazy247.xyz/order/payment-return'
    depends_on:
      - d

volumes:
  mariadb_data_local:
    driver: local
